# Generated by Django 4.2.2 on 2023-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reactiontime_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rank', models.CharField(max_length=255)),
                ('best_rank', models.CharField(max_length=255)),
                ('game_time', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
